node-fetch installed. Fixed error 'TypeError: o is not a function'. 'const fetch = require('node-fetch').default;'. Still investigating why '.default' is needed